name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake build-essential libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev pkg-config

          # - name: Build
          #   run: |
          #     mkdir build
          #     cd build
          #     cmake ..
          #     cmake --build .

          # - name: Run tests
          #   run: |
          #     cd build
          #     ctest --output-on-failure
